### ISSUE TITLE
Improve canStakeAndWithdraw

### ISSUE THREAD

**Issue by phahulin** [poanetwork/posdao-test-setup#29]
Function [`canStakeAndWithdraw`](https://github.com/poanetwork/posdao-test-setup/blob/b60994bd16dfdeab39d3cba7a29f7d105a083cd4/utils/canStakeAndWithdraw.js) which should determine if we are in a time window to do stakes or withdraw, is not entirely correct because it checks only  _current_ block, so if we are _one block before_ the window is closed, it will return `true`, however our tx will not have time to get into current block and will fail in the next block.

**Comment by vkomenda** [comment]
Can we instead add atomic staking and withdrawal in `posdao-contracts` which return the status of the operation: success or failure with an error?
Otherwise any solution would have to pass the block number and recheck it later when staking or withdrawal is performed, which is not ideal.

**Comment by DemiMarie** [comment]
Can we just _try_ to stake or withdraw, and catch the exception if it fails?

**Comment by vkomenda** [comment]
> Can we just _try_ to stake or withdraw, and catch the exception if it fails?

Sure we can. The value of the exception should tell to retry.

**Comment by phahulin** [comment]
The exception will only tell us that tx failed (was reverted).
Probably, we should write a wrapper function that
1. waits until `areStakeAndWithdrawAllowed` is true, and then sends the tx
2. if tx fails it re-checks `areStakeAndWithdrawAllowed` again, if it's `false` now, wait until it becomes `true` and then retry again
3. if it still fails - fail the test.

**Comment by vkomenda** [comment]
> 1. waits until `areStakeAndWithdrawAllowed` is true, and then sends the tx

That sounds too complex and there is still no atomicity.

**Comment by phahulin** [comment]
What do you mean by atomicity here?

**Comment by vkomenda** [comment]
I mean that the call is still composed of two steps: the check and the operation. If those happen to fall into different blocks, we have the previous problem with the check result obsolescence that you mentioned above. To solve this, I think that the operation should somehow perform the check "atomically" meaning that, if the operation fails after a successful check, the check is presumed to had failed. To do this in the test would complicate the presentation. But if you think we should keep the contract API simple, you could have steps 1-3 above.

**Comment by phahulin** [comment]
I think we can't get a meaningful error message from a transaction, so that if it fails we can't tell was it because of the missed staking window or because of some other reason.
@varasev maybe you could help us here with some ideas?

**Comment by varasev** [comment]
> To solve this, I think that the operation should somehow perform the check "atomically"

We could make the `stake`/`addPool` function return a boolean value, but the problem is that we can't read that value by web3. The returned values can only be read by other contracts (not by clients). However, we could use the [`Staked` event](https://github.com/poanetwork/posdao-contracts/blob/9c98b5e584367a2fee304a2f1c1a1ada3ce4cb26/contracts/abstracts/ValidatorSetBase.sol#L214) instead: it is emitted when the stake was successful.

So, if the `Staked` event is not emitted, then we should wait until `areStakeAndWithdrawAllowed` returns `true` and then try again.

Also, in order to determine if we're in a time window to do stakes or withdraw, we could check the current block number by [the rules](https://github.com/poanetwork/posdao-contracts/blob/9c98b5e584367a2fee304a2f1c1a1ada3ce4cb26/contracts/ValidatorSetAuRa.sol#L115), so if the current block number is close to the disallowed period start block, then sleep for `stakeWithdrawDisallowPeriod()` blocks and then wait until `areStakeAndWithdrawAllowed` returns `true` before trying to call staking/withdrawal functions.

E.g., if `currentBlock < stakingEpochStartBlock() + stakingEpochDuration() - stakeWithdrawDisallowPeriod() - 5` then sleep for `stakeWithdrawDisallowPeriod()` blocks.

**Comment by vkomenda** [comment]
Maybe the sleep can be extended to invocations within the disallowed period like so:
```
let blocksUntilEnd = stakingEpochDuration() + stakingEpochStartBlock() - currentBlock;
if (blocksUntilEnd >= 0) && (blocksUntilEnd < stakeWithdrawDisallowPeriod() + 5) {
    sleepBlocks(blocksUntilEnd + 1);
}
```

**Comment by varasev** [comment]
@vkomenda The `blocksUntilEnd` in your code is always `>= 0` because the `currentBlock` is always less than `stakingEpochStartBlock()`.

**Comment by varasev** [comment]
Also, note that anyway after sleeping we should wait until `areStakeAndWithdrawAllowed()` returns `true` because staking/withdrawal is not allowed during the first blocks of new staking epoch until new validator set is applied (see the first part of [the rule](https://github.com/poanetwork/posdao-contracts/blob/9c98b5e584367a2fee304a2f1c1a1ada3ce4cb26/contracts/ValidatorSetAuRa.sol#L115)).

**Comment by phahulin** [comment]
Then we can just check every block until `areStakeAndWithdrawAllowed()` becomes `true`, but at most `stakingEpochDuration() + stakeWithdrawDisallowPeriod()` blocks, right?

**Comment by varasev** [comment]
Waiting for `stakingEpochDuration()` is too long. It's enough to wait for `stakeWithdrawDisallowPeriod()` plus a few blocks until new validator set is applied.

**Comment by DemiMarie** [comment]
Atomicity is either impossible or useless, since transaction execution is inherently asynchronous.  The best we can do is to ensure that our transactions are idempotent.
